<a href="https://colab.research.google.com/github/mssarahhussain/summer2026internship/blob/main/Week_1_Notebook_Sarah_Hussain_Titanic_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving titanicdataset.csv to titanicdataset.csv

In [ ]:
df = pd.read_csv("titanicdataset.csv")
print("Dataset loaded")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

#1 printing the first 5 rows with df.head()
df.head()

Dataset loaded
Number of rows: 1309
Number of columns: 9

   Passengerid   Age     Fare  Sex  sibsp  Parch  Pclass  Embarked  2urvived
0            1  22.0   7.2500    0      1      0       3       2.0         0
1            2  38.0  71.2833    1      1      0       1       0.0         1
2            3  26.0   7.9250    1      0      0       3       2.0         1
3            4  35.0  53.1000    1      1      0       1       2.0         1
4            5  35.0   8.0500    0      0      0       3       2.0         0

In [ ]:
#2 selecting specific columns
new_columns = df[["Passengerid","Age", "Fare", "Sex", "2urvived"]]
new_columns.head()

   Passengerid   Age     Fare  Sex  2urvived
0            1  22.0   7.2500    0         0
1            2  38.0  71.2833    1         1
2            3  26.0   7.9250    1         1
3            4  35.0  53.1000    1         1
4            5  35.0   8.0500    0         0

In [ ]:
#3 only keeping the survivors
survivors = df[df["2urvived"] == 1]
print("Number of survivors:", len(survivors))
survivors.head()

Number of survivors: 342

   Passengerid   Age     Fare  Sex  sibsp  Parch  Pclass  Embarked  2urvived
1            2  38.0  71.2833    1      1      0       1       0.0         1
2            3  26.0   7.9250    1      0      0       3       2.0         1
3            4  35.0  53.1000    1      1      0       1       2.0         1
8            9  27.0  11.1333    1      0      2       3       2.0         1
9           10  14.0  30.0708    1      1      0       2       0.0         1

In [ ]:
#4 filter with 2 conditions
young_high_fare = df[(df["Age"] < 18) & (df["Fare"] > 20)]
young_high_fare[["Passengerid","Age", "Fare", "Sex", "2urvived"]].head()

    Passengerid   Age     Fare  Sex  2urvived
7             8   2.0  21.0750    0         0
9            10  14.0  30.0708    1         1
16           17   2.0  29.1250    0         0
24           25   8.0  21.0750    1         0
43           44   3.0  41.5792    1         1

In [ ]:
#5 Count missing values with isna() and sum()
missing_values = df.isna().sum()
#missing_values
missing_values[missing_values > 0]

Embarked    2
dtype: int64

In [ ]:
#6 Fill missing ages
df_clean = df.copy() #make copy so you don't change original data
median_age = df_clean["Age"].median() #GEt the median age
df_clean["Age"] = df_clean["Age"].fillna(median_age) #fill empty values with median age

print("Median age:", median_age)
print("Missing ages before:", df["Age"].isna().sum())
print("Missing ages after:", df_clean["Age"].isna().sum())

Median age: 28.0
Missing ages before: 0
Missing ages after: 0

In [ ]:
#7 Remove duplicate rows
duplicate_count = df_clean.duplicated().sum()
print("Duplicate rows before removal:", duplicate_count)
df_clean = df_clean.drop_duplicates()
print("Rows after removal:", len(df_clean))

Duplicate rows before removal: 0
Rows after removal: 1309

In [ ]:
#8 Survival rate of each sex
survival_by_sex = df_clean.groupby("Sex")["2urvived"].mean() * 100
#Groupby seperates into female and male passenger, "2urvived" selects column
#mean calculates the avg of 0 and 1s --> survival rate
# * 100 to make it percentage
survival_by_sex.round(2)

Sex
0    12.93
1    50.00
Name: 2urvived, dtype: float64

In [ ]:
#9 Group by passenger class
class_summary = df_clean.groupby("Pclass").agg(
    passenger_count = ("2urvived", "count"),
    average_age = ("Age", "mean"),
    average_fare = ("Fare", "mean"))
class_summary.round(2)

        passenger_count  average_age  average_fare
Pclass
1                   323        37.81         87.51
2                   277        29.42         21.18
3                   709        25.75         13.30

In [ ]:
#10 Merge 2 dataframes
class_info = pd.DataFrame({
    "Pclass": [1, 2, 3],
    "class_name": ["First Class", "Second Class", "Third Class"]
})

merged_df = df_clean.merge(class_info, on="Pclass")

merged_df[["Pclass", "class_name", "Sex", "Age", "2urvived"]].head()
#The merge() function combines two DataFrames using their shared pclass column. It adds the class name to each passenger based on their passenger-class number.

   Pclass   class_name  Sex   Age  2urvived
0       3  Third Class    0  22.0         0
1       1  First Class    1  38.0         1
2       3  Third Class    1  26.0         1
3       1  First Class    1  35.0         1
4       3  Third Class    0  35.0         0